version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5001:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=prismaDB
volumes:
  db: